version: 2

models:
    - name: dl_accounts
      description: Accounts data in datalake layer which is coming from raw layer. This is an incremental model with SCD Type 1 data.
      columns:
        - name: id
          description: Primary key for accounts table.
          tests:
              - unique
              - not_null