version: 2

models:
    - name: dl_accounts
      description: Accounts data in datalake layer which is coming from raw layer. This is an incremental model with SCD Type 1 data.
      columns:
        - name: id
          description: Primary key for accounts table.
          tests:
              - unique
              - not_null

    - name: dl_opportunity
      description: The data from raw_sf_opportunity table is loaded into the datalake layer with incremental load which is SCD Type 1.
      columns:
        - name: id
          description: Primary key for opportunity table.
          tests:
              - unique
              - not_null
        - name: accountid
          description: Account ID which is similar to ID in the accounts table